project:
  type: website

website:
  title: "panelize"
  reader-mode: true
  repo-url: https://github.com/coatless-quarto/panelize/
  repo-actions: [edit, issue]
  sidebar:
    style: "floating"
    search: true
    tools:
      - icon: github
        href: https://github.com/coatless-quarto/panelize/
    contents: 
      - text: "Home"
        file: index.qmd
      - text: "Install"
        file: qpanelize-install.qmd
      - section: "Panelize Demos"
        contents:
        - text: "Code Cells"
          href: qpanelize-cell.qmd
        - text: "Python to Pyodide"
          href: qpanelize-pyodide.qmd
        - text: "R to webR"
          href: qpanelize-webr.qmd
      - section: "Support"
        contents:
        - text: "Submit an issue"
          href: https://github.com/coatless-quarto/panelize/issues/new/choose
      - section: "Extra"
        contents:
        - qpanelize-release-notes.qmd

format: 
  html:
    toc: true

engine: knitr